export const networkConfigs = {
  ethereum: {
    name: "Ethereum",
    rpcUrl: "https://ethereum-rpc.publicnode.com",
    chainId: 1,
    chainIdHex: "0x1",
    icon: "./img/eth.png",
    showInUI: true,
  },
  arbitrum: {
    name: "Arbitrum",
    rpcUrl: "https://1rpc.io/arb",
    chainId: 42161,
    chainIdHex: "0xa4b1",
    icon: "./img/arb.png",
    showInUI: true,
  },
  optimism: {
    name: "Optimism",
    rpcUrl: "https://mainnet.optimism.io",
    chainId: 10,
    chainIdHex: "0xa",
    icon: "./img/op.png",
    showInUI: true,
  },
  base: {
    name: "Base",
    rpcUrl: "https://base-rpc.publicnode.com",
    chainId: 8453,
    chainIdHex: "0x2105",
    icon: "./img/base.png",
    showInUI: true,
  },
  zksync: {
    name: "ZKsync",
    rpcUrl: "https://mainnet.era.zksync.io",
    chainId: 324,
    chainIdHex: "0x144",
    icon: "./img/zksync.png",
    showInUI: false,
  },
  scroll: {
    name: "Scroll",
    rpcUrl: "https://rpc.scroll.io",
    chainId: 534352,
    chainIdHex: "0x82750",
    icon: "./img/scroll.png",
    showInUI: false,
  },
  zkevm: {
    name: "zkEvm",
    rpcUrl: "https://zkevm-rpc.com",
    chainId: 1101,
    chainIdHex: "0x44d",
    icon: "./img/zkevm.png",
    showInUI: false,
  },
  sepolia: {
    name: "Sepolia",
    rpcUrl: "https://rpc.sepolia.org",
    chainId: 11155111,
    chainIdHex: "0xaa36a7",
    icon: "./img/sepolia.png",
    showInUI: false,
  },
};
